### ISSUE TITLE
Disable Logging mid call

### ISSUE THREAD

**Issue by chrisgdg** [GenuineChannels/GenuineChannels#1]
Hi,
We've discovered an issue if you disable logging during a remoting call using
`Belikov.GenuineChannels.Logbook.GenuineLoggingServices.StopLogging();`

ie, if you call a method on the server object that calls the StopLogging method, there is a null reference exception.

I've managed to trace this to GenuineUniversalServerTransportSink.HandleIncomingMessage

It gets the binaryLogWriter at the beginning of the method, and then after passing the call to the `_nextChannelSink`, it attempts to use `this.ITransportContext.BinaryLogWriter` which is now null.

adding
`binaryLogWriter = message.ITransportContext.BinaryLogWriter;`

just before
`switch (serverProcessing)`
fixes the issue

**Comment by yallie** [comment]
@chrisgdg Thanks for reporting!
