### ISSUE TITLE
How to migrate from v2.5.9.5 to the latest version

### ISSUE THREAD

**Issue by lcetinapta** [GenuineChannels/GenuineChannels#8]
Hi, recently I got to work on a project that was built on .NET 2.0 using Genuine channels v 2.5.9.5.
My task is to migrate it to .NET 4.8.
Is it possible to do an in-place replacement of Genuine channels library or it is not that easy?

Thanks

**Comment by yallie** [comment]
Hello, 

There should not be any incompatible changes in the latest version.
I think that drop-in replacement should be possible.

Cheers, Alex
